# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that Flask will run on
EXPOSE 5000

# Define environment variable to prevent Python from writing pyc files
ENV PYTHONUNBUFFERED=1

# Run the Flask app when the container starts
CMD ["python", "app.py"]
